# Generated by Django 5.2.15 on 2026-06-08 12:09

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=50, unique=True)),
                ('ward_type', models.CharField(choices=[('OPD', 'OPD Daycare / Minor Triage Bay (25 Beds)'), ('GENERAL', 'General Medical Inpatient Ward (25 Beds)'), ('ICU', 'High-Tier Intensive Trauma ICU Suite (25 Beds)'), ('RESERVE', 'Dynamic Surge Expansion Reserve Ward (25 Beds)')], default='GENERAL', max_length=30)),
                ('occupied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty_branch', models.CharField(choices=[('PRIMARY_CARE', 'Primary & General Care (GP / Family Physician)'), ('CARDIOLOGY', 'Cardiology (Heart & Vascular Specialists)'), ('DERMATOLOGY', 'Dermatology (Skin, Hair & Nails)'), ('ENDOCRINOLOGY', 'Endocrinology (Hormones & Metabolism)'), ('GASTROENTEROLOGY', 'Gastroenterology (Digestive & Liver)'), ('NEUROLOGY', 'Neurology (Brain & Nervous System)'), ('PULMONOLOGY', 'Pulmonology (Respiratory & Lung Care)'), ('NEPHROLOGY', 'Nephrology (Kidney Health & Dialysis)'), ('RHEUMATOLOGY', 'Rheumatology (Joint & Autoimmune)'), ('GEN_SURGERY', 'General Surgery (Abdominal & Soft Tissue)'), ('ORTHOPEDICS', 'Orthopedics (Musculoskeletal & Bones)'), ('NEUROSURGERY', 'Neurosurgery (Brain & Spine Surgical)'), ('OBGYN', 'Obstetrics & Gynecology (OB/GYN)'), ('OPHTHALMOLOGY', 'Ophthalmology (Vision Care & Surgery)'), ('ENT', 'Otolaryngology (Ear, Nose & Throat)'), ('EMERGENCY', 'Emergency Medicine Specialists (ER)'), ('CRITICAL_CARE', 'Critical Care / ICU Specialists'), ('RADIOLOGY', 'Radiology (Imaging Diagnostics)'), ('PATHOLOGY', 'Pathology (Advanced Laboratory Medicine)'), ('PSYCHIATRY', 'Psychiatry (Mental Health Services)'), ('PHYSIOTHERAPY', 'Physiotherapy & Rehabilitation Unit'), ('INFECTIOUS_DISEASE', 'Infectious Disease Isolation Unit')], default='PRIMARY_CARE', max_length=50)),
                ('qualification', models.CharField(default='MBBS, MD', max_length=50)),
                ('is_active_on_shift', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=15)),
                ('age', models.IntegerField(default=30)),
                ('patient_relative_name', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_relative_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField()),
                ('symptoms', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fever', 'Fever'), ('Headache', 'Headache'), ('Body pain', 'Body pain'), ('Fatigue', 'Fatigue'), ('Cold', 'Cold'), ('Cough', 'Cough'), ('Vomiting', 'Vomiting'), ('Diarrhea', 'Diarrhea'), ('Skin rash', 'Skin rash'), ('Loss of appetite', 'Loss of appetite'), ('Chest pain', 'Chest pain'), ('Palpitations', 'Palpitations'), ('Shortness of breath', 'Shortness of breath'), ('Swollen legs', 'Swollen legs'), ('Dizziness', 'Dizziness'), ('Fainting', 'Fainting'), ('Itching', 'Itching'), ('Skin redness', 'Skin redness'), ('Dry skin', 'Dry skin'), ('Hair loss', 'Hair loss'), ('Acne', 'Acne'), ('Pigmentation', 'Pigmentation'), ('Excessive thirst', 'Excessive thirst'), ('Weight gain', 'Weight gain'), ('Weight loss', 'Weight loss'), ('Increased urination', 'Increased urination'), ('Stomach pain', 'Stomach pain'), ('Bloating', 'Bloating'), ('Acid reflux', 'Acid reflux'), ('Severe headache', 'Severe headache'), ('Memory loss', 'Memory loss'), ('Numbness', 'Numbness'), ('Seizures', 'Seizures'), ('Wheezing', 'Wheezing'), ('Breathing difficulty', 'Breathing difficulty'), ('Chest tightness', 'Chest tightness'), ('Swelling', 'Swelling'), ('Reduced urine', 'Reduced urine'), ('Blood in urine', 'Blood in urine'), ('High BP', 'High BP'), ('Joint pain', 'Joint pain'), ('Joint swelling', 'Joint swelling'), ('Stiffness', 'Stiffness'), ('Abdominal pain', 'Abdominal pain'), ('Hernia bulge', 'Hernia bulge'), ('Trauma', 'Trauma'), ('Bone pain', 'Bone pain'), ('Difficulty walking', 'Difficulty walking'), ('Head injury', 'Head injury'), ('Brain tumor symptoms', 'Brain tumor symptoms'), ('Paralysis', 'Paralysis'), ('Pelvic pain', 'Pelvic pain'), ('Irregular periods', 'Irregular periods'), ('Pregnancy complications', 'Pregnancy complications'), ('Blurred vision', 'Blurred vision'), ('Eye pain', 'Eye pain'), ('Red eye', 'Red eye'), ('Ear pain', 'Ear pain'), ('Hearing loss', 'Hearing loss'), ('Sore throat', 'Sore throat'), ('Nasal blockage', 'Nasal blockage'), ('Severe bleeding', 'Severe bleeding'), ('Unconsciousness', 'Unconsciousness'), ('Poisoning', 'Poisoning')], max_length=775, null=True)),
                ('active_diagnosis', models.TextField(default='Pending Evaluation Verification')),
                ('prior_ailments', models.TextField(blank=True, default='None')),
                ('ordered_diagnostics', models.CharField(default='None (Routine Triage)', max_length=250)),
                ('admission_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('bill_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('doctors_notes', models.TextField(blank=True, default='Clinical admission evaluation complete.', null=True)),
                ('doctors_visiting_time', models.CharField(default='09:00 AM - 11:30 AM', max_length=50)),
                ('status', models.CharField(default='Admitted', max_length=50)),
                ('bed_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.bed')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.doctor')),
            ],
        ),
    ]
